import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SideBar from "@/components/SideBar";

export const metadata = {
  title: "Spotify - Web Player: Music for everyone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="main flex p-2">
      {" "}
      <SideBar />
      <div className="layout flex flex-col rounded-lg">
        <Header />
        {children}
      </div>
      <Footer />
    </div>

    // <html lang="en">
    //   <body>
    //     {" "}
    //     <div className="main flex p-2">
    //       {" "}
    //       <SideBar />
    //       <div className="home flex flex-col rounded-lg">
    //         <Header />
    //         {children}
    //       </div>
    //       <Footer />
    //     </div>
    //   </body>
    // </html>
  );
}
